[package]
name = "csv_data_on_page"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.1"
rocket = { version="0.5.1" ,features = ["json"]}
serde = { version ="1.0.217",features = ["derive"] }
tokio = { version ="1.43.0",features = ["full"]}
